language: python
python:
  - "3.5"
install: "pip install -r test-requirements.txt"
script: tox -e pep8,py35,cover
notifications:
  email:
    recipients:
      - hieulq19@gmail.com
      - tranhuucuong91@gmail.com 
    on_success: change
on_failure: always
